* my personal brand
- [[https://www.monster.com/career-advice/article/build-your-brand][build-your-brand]] in eight steps
  brand is a collection of assumptions about quality, appeal and reliability made
  in response to repeated experience with a variety of possible products, people, or
  services.  Below are the eight steps to build personal brand.
  1. Identify primary product to offer others.
     - software development
     - business consulting
     - web design, web programming
     - IT
  2. Identify core values.
     - Because I enjoy the excitement in taking risk, I seek gaining experience from being an entrepreneuer starting my own business.  Influencing others
       comes from being recognized as an expert, and so I'd want to create a company with a chance of becoming an expert.  Also, I can have more control 
       in general in the direction of a company, and set my own hours if I start my own business.  This control also will allow me to define an aesthetically 
       pleasing environment in step with my company brand.  I value being respected for the creative work I do and feel that more opportunity to express my 
       creativity will come from creating my own company.  Lastly, I value being organized and more efficient.
  3. Identify passions.
     - Violin music
     - Python, R, Django,and web design/web programming
     - Mathematics
     - Improving my web presence
  4. Identify talents.
     1. computer programming
     2. Musical
     3. Analytical
     4. Athletic
     5. multi-lingual
     6. methodical
     7. data manipulation
  5. Choose top five talents you do best and enjoy the most.
     1,2,3,5,6
  6. Weave the five items into a statement of your specialty.
     Specialty in business intelligence and Information Systems to build customized open-sourced software and infrastructure solutions
  7. Write a paragraph emphasizing specialty and your five key talents using your most important values, passions and skills.
     Interpret data for better business decisions that comes from understanding and predicting market trends.  Create customized designed 
     experiments to obtain data.  Use as part of tool set the open-sourced statistical package R, programming language Python, and python-based 
     web frameworks.  Use methodical method to create reproducible research and data analysis with the Git Version Control System at Github.

     From all learned from efforts of creating reproducible research, I am dedicated to communicate mathematics and promote mathematical literacy online.
     
  8. Add a tag line to your brand
     - Math, Comp, and Art to Stay in the Market Smart
- [[http://www.hongkiat.com/blog/handpicked-printed-brochures/][Brochure Examples]]
  *** Respond to two posts
    DEADLINE: <2017-09-18 Mon>
* how to write a business message
   - first step in writing process is planning business messages.  To plan any message, 
     first analyze the situation by defining your purpose and developing a profile of your audience.
   - main ideas when writing for the business are recommendations, a conclusion, or a request
   - subject line of a message should clearly indicate the topic of the message
   - the writer can help readers by providing an organizational structure to the message
   - a well-organized message groups related ideas and presents them in logical order
   - the close of a message often summarizes or reiterates the main idea
* how to write a business proposal
   - To begin, first identify the goal of your business proposal.  What are you trying to accomplish in writing this proposal?
     Persuassion may include your assessment of the situation, an explanation of what caused the problem and how it can be fixed.
   - To avoid confusion, the best way to begin a business proposal is to give a brief overview of the proposal -- what the proposal
     will cover, how it will be organized, and what the reader should expect from reading the proposal.  This kind of approach should
     be expressed as clearly as possible so the reader can use it as a guide to the proposal itself.
   - Explain why your company is the best choice for the job.  You can tell reader that the company "knows how you feel" to identify the
     key parts to the job/contract.  Make a personal connection between company and customer.
   - Define the problem and situation.  Provide explanation for why you reached your conclusion.  Assess the situation, identify and 
     explain the source of problems, and describe how it will be remedied.
   - Focus attention on how to fix the problem rather than focusing on placing any kind of blame
   - Offer workplan to effectively tell customer how the job will proceed.  Use bullet points that focus on a separate aspect of the work plan.
   - Provide timetable that wil best illustrate your plan.  Provide only important information that is easy to access at a glance.
   - Close with a short persuasive closing.  Repeat key words.  Can choose to offer some kind of pledge.
